services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KonradMichalik\PagetreeFacets\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Token/Token.php'
      - '../Classes/Api/FilterContext.php'
      - '../Classes/Event/*'

  KonradMichalik\PagetreeFacets\Controller\FacetsModalController:
    public: true
